services:
  db:
    image: postgres:15
    container_name: figgie-db
    environment:
      - POSTGRES_DB=figgie
      - POSTGRES_USER=figgie
      - POSTGRES_PASSWORD=secret_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  figgie-server:
    build:
      context: .
      dockerfile: figgie_server/Dockerfile
    container_name: figgie-server
    depends_on:
      - db
    ports:
      - "5050:5000"
    environment:
      - NUM_PLAYERS=4
      - TRADING_DURATION=60
      - POSTGRES_HOST=db
      - POSTGRES_DB=figgie
      - POSTGRES_USER=figgie
      - POSTGRES_PASSWORD=secret_password
    restart: unless-stopped

volumes:
  pgdata:
    driver: local
