services:
  figgie-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: figgie-server
    ports:
      - "8000:5000"
    environment:
      - PORT=5000
      - NUM_PLAYERS=4
      - TRADING_DURATION=60
    restart: unless-stopped
