version: "3.8"

services:
  figgie-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: figgie-server
    ports:
      - "8000:5000"
    environment:
      - PORT=5000
      - NUM_PLAYERS=4
      - TRADING_DURATION=60
      - DB_PATH=/data/figgie.db  # path for SQLite DB file
    volumes:
      - sqlite_data:/data        # persistent storage for SQLite
    restart: unless-stopped

volumes:
  sqlite_data:
    driver: local
